[#113] - Radius not an option
bigbite/themer pull request #117
Opened 2024-10-07 14:06 UTC by thatisrich

## Description

[#113](https://github.com/bigbite/themer/issues/113) - This PR aims to introduce a `border radius` option alongside the current border option.

This approach aims to replicate the border radius option found [within the block editor](http://bigbite.im/i/NQelE1), as it appears that there is currently no `core` component which handles a radius option, likewise neither do the components [BorderBoxControl](https://developer.wordpress.org/block-editor/reference-guides/components/border-box-control/) or [BorderControl](https://developer.wordpress.org/block-editor/reference-guides/components/border-control/).

**NOTE - This PR relies on the [block preview PR](https://github.com/bigbite/themer/pull/111) which is yet to be merged. The reason for this was to ensure the border radius addition worked correctly across both the `code` and `visual` previews.**

In this approach it is possible to set a singular `Linked` value for the border radius and `Unlinked` values, where each corner can be controlled independently.

**Current known bugs**
- When setting a value with the slider prior to a value being set in the `UnitControl`, the measurement value is left blank and a basic number is assigned to the value - this does not work with the radius option and therefore causes unexpected side effects

## Change Log

- `src/editor/components/StylesBorder.js` - Including radius component in the layout
- `src/editor/components/StylesBorderRadius.js` - The new component

## Steps to test

- Navigate to the Styles Editor page
- Select an element or block, such as `Button`
- Scroll down in the styles panel to the bottom where `Border and radius` is in view
- Adjust the `Radius` Linked value using the input box
- When the `Visual` view is selected, notice the border radius will change accordingly
- When the `Code` view is selected, notice the value of the radius property will change accordingly
- Adjust the `Radius` Linked value using the range slider
- Notice the changes are reflected in both views
- Click on the `Unlink` button to reveal 4 input boxes, one for each corner of the element
- Update the value in each box
- Notice the changes are reflected in both the `Visual` and `Code` views
- Follow these steps on other blocks and elements

## Screenshots/Videos

[A demo showing various interactions with the radius setting and the visual preview](http://bigbite.im/v/BJv9HP)
[A demo showing various interactions with the radius setting and the code preview](http://bigbite.im/v/Otc2gG)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-07 18:19 UTC, thatisrich commented
On further testing I noticed a bug in which the value would be stripped when toggling between `Linked` and `Unlinked` values. This has now been addressed and works as expected and fallbacks are in place.

[A demo showing how the toggles work when stripping certain values can be seen here](http://bigbite.im/v/3OduWl)

2025-01-03 11:57 UTC, g-elwell requested changes
Hey @thatisrich - thanks for working on this! It works well during my testing, however whilst comparing things to Gutenberg I noticed there is a [BorderRadiusControl](https://github.com/WordPress/gutenberg/tree/8dd99ede394c871a94bafc33a71abb0cf24c7bc8/packages/block-editor/src/components/border-radius-control) component in there, were you aware of this, do you think we'd be able to update this PR to utilise it?

2025-01-06 08:53 UTC, g-elwell requested changes
Thanks for looking into the WordPress component, this works well and using it means less maintenance for us 🙌 

I don't think border radius will be needed as a standalone component, so IMO we should just use the `BorderRadiusControl` within the `StylesBorder` component, and add a new `onChange` callback for it, just to keep things a bit neater, e.g:

```js
const onRadiusChange = ( newValue ) => {
	let config = structuredClone( userConfig );
	config = set( config, `${ selector }.radius`, newValue );
	setUserConfig( config );
};
```

2025-01-06 08:53 UTC, g-elwell commented on src/editor/components/StylesBorder.js
> +				{ __( 'Border and radius', 'themer' ) }
Please can we keep this as "Border" as radius is just a part of the border styles

2025-01-06 10:50 UTC, thatisrich commented
When further testing the `BorderRadiusControl` component after moving it, I noticed an issue when a deleted radius value did not have a fallback resulting in an unexpected border radius being applied in both Themer and on the front end. The `onRadiusChange` function has been adapted to account for this and, (thanks to the suggestions!) should streamline the `StylesBorder` component and maintenance moving forward.

Please [see here](http://bigbite.im/v/e2LnQr) for an updated screen recording showing the minor UI tweaks.

2025-02-24 17:52 UTC, g-elwell approved these changes
We had one small bug when there was no value defined, so pushed a quick fix to add optional chaining before trying to access the value

Other than that, this is working great for me - thanks @thatisrich !

2025-02-24 17:52 UTC, merged