feature/94-adjust-settings
bigbite/themer pull request #120
Opened 2024-12-02 15:10 UTC by chrishall0

Draft PR for WIP. Have site settings working. Need to handle any nested objects and components for these will need building out. Currently trying to get individual Block settings to work

## Description

## Change Log

-
-
-

## Steps to test

## Screenshots/Videos

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2025-01-02 11:44 UTC, g-elwell requested changes
@chrishall0 thanks for picking this up! It's a great start, I have a couple of initial thoughts that I'd like to run by you:
- Although valid in the schema, allowing all settings to be set on every block feels a bit overwhelming, I wonder if we should limit this for the time being and just provide a UI for the top level 'site' settings
- Some of the components have incorrect names / JSDoc comments (e.g: `Settings` is called `Styles` - I guess left over from cloning components), some are missing JSDoc comments. Could you spend a bit of time going through and checking these?
- The colour palette setting is being saved to `.custom` but I think this should be `.theme`, so that the colours we choose are available elsewhere, and also so we can edit existing theme.json colour values.

Overall it looks good, I think we'd be more refining and testing this than anything else. If we decide to limit to site settings only I hope this will make it easier to test, and we can loop Jonny in for UI/UX input once we're happy everything is working, which shouldn't take too long.

2025-01-02 14:05 UTC, g-elwell requested changes
Cheers for making those changes so quickly @chrishall0

Sorry if I'm drip feeding here, just been getting to grips with things and doing some more testing...

There are a few other values which I think should be reading/saving to `.theme` rather than `.custom` so they show up properly:
- Gradient
- Duotone
- Shadow presets
- Font Families
- Font Sizes

In `CodeView` could we display the settings object when we navigate to the `/settings` panel? This will also help us see how the UI affects the settings object. It's a bit large so can be hard to see what you're editing, but better than nothing for now.

Editing spacing units seems as though it's not working correctly. Adding a value will overwrite an existing value and I'm unable to remove any of the existing values. Also, perhaps the UI should only allow specific preset values rather than free-text input.

Please can we change "Custom Settings" title to "Custom CSS" and rename component to `SettingsCustomCSS` to match?

Testing this with the code view in place using one of the core WordPress themes like twentytwentyfive or twentytwentyfour you can see certain values from theme.json which aren't supported. I don't necessarily think we need to support everything 100% but it could be worth documenting what is/isn't supported and we can add things if needed over time. Depends on how straightforward this is.

2025-01-09 11:40 UTC, chrishall0 commented
Missing settings: 

**Spacing Settings**

spacingScale 
```
    "spacingScale": {
      "theme": {
        "operator": "*",
        "increment": 1.5,
        "steps": 7,
        "mediumStep": 1.5,
        "unit": "rem"
      }
    },
```
spacingSizes
```
"spacingSizes": {
      "theme": [
        {
          "name": "Tiny",
          "size": "10px",
          "slug": "20"
        },
        {
          "name": "X-Small",
          "size": "20px",
          "slug": "30"
        },
        {
          "name": "Small",
          "size": "30px",
          "slug": "40"
        },
        {
          "name": "Regular",
          "size": "clamp(30px, 5vw, 50px)",
          "slug": "50"
        },
        {
          "name": "Large",
          "size": "clamp(30px, 7vw, 70px)",
          "slug": "60"
        },
        {
          "name": "X-Large",
          "size": "clamp(50px, 7vw, 90px)",
          "slug": "70"
        },
        {
          "name": "XX-Large",
          "size": "clamp(70px, 10vw, 140px)",
          "slug": "80"
        }
      ]
    }
```

**Dimension Settings**
aspectRatios
```
"aspectRatios": {
      "theme": [
        {
          "name": "Example",
          "slug": "example",
          "ratio": "16/9"
        },
      ]
```

I will create tickets for these missing components

2025-01-09 14:48 UTC, g-elwell requested changes
This is shaping up really well @chrishall0 - I love it!

## Editing colours

When editing a colour, can we also have the ability to update the name/slug?

https://github.com/user-attachments/assets/5e09ff22-50d1-4262-ad7b-a2ba37828dcd

The same goes for gradients and duotone - perhaps we could reuse the same component for both adding and editing?

## Design changes

Please can we remove:
- One layer of padding/border from the site settings area so the accordion is flush to the sides of the panel
- The first item/title `Site Settings` as this duplicates the content above
- The first heading inside each section, as this duplicates the accordion panel title

![96070](https://github.com/user-attachments/assets/929c621d-3002-4c6c-aeee-b7bb6e87e9c0)

## Navigation

Would it be possible/straightforward for the navigation to the settings area to be a 'toggle' - in the sense when you click the button whilst the settings is open, it sends you back to the previous area you were editing?

### Colour bugs/quirks

If you add a colour without touching the colour picker, it adds a new, blank, colour, and you can't click this to edit or delete it. Not sure if it's a bug when you try to click it, or if we should just add the colour as `#000` if not interacted with, which should resolve the issue.

When a user is entering a slug, can we convert spaces to `-`?

2025-03-03 08:50 UTC, g-elwell requested changes
Thanks for the latest changes @chrishall0 

The modals are still looking a bit inconsistent, please can we adjust them all to use the `title` prop, and ensure they have the correct add/edit labels?

- Duotone modal - looks great ✅ 
- Gradient modal - can this say Add New Gradient, Edit Gradient
- Font Families modal - can this say Add New Font Family, Edit Font Family and use the `title` prop
- Font Face modal (inside of font families modal) - Can this say Add New Font Face, Edit Font Face and use the `title` prop
- Font Sizes modal - Can this say Add New Font Size, Edit Font Size and use the `title` prop
- Shadows modal - Can this say Add New Shadow, Edit Shadow and use the `title` prop

Can we adjust the display of the font face inside of the font family modal? IMO this should:
- Be above the save/delete buttons
- Avoid stretching the modal width excessively (add a max-width, or stack vertically?) If there are many stacked vertically, we'd need to ensure this looks okay too
- Show more info in the listing (see screenshot from my default config, all the items look the same so you can't tell what each one is for):
![38665](https://github.com/user-attachments/assets/4368f033-810a-4fc2-a6c8-aff13c9809a2)


I hit a small bug when testing, by adding a gradient without selecting an angle, when you then click back in to view/edit this gradient, the component will crash. Can we add a check in the component to prevent crashing when the orientation doesn't exist? Also it might make sense to provide a default value of `0` when adding a new gradient, but I think the check would be a good idea regardless incase we load a theme.json with missing data.

2025-03-12 10:31 UTC, g-elwell approved these changes
Works for me, thanks for making those changes @chrishall0 !

2025-03-12 10:31 UTC, merged